#ifndef BOOTSTRAP_CREDENTIALS_H
#define BOOTSTRAP_CREDENTIALS_H

static const char bootstrap_cert_pem[] =
"-----BEGIN CERTIFICATE-----\r\n"
"MIIC7zCCApWgAwIBAgIRAIo9Sf1Du2dT2/LwL8OIyFwwCgYIKoZIzj0EAwIwEjEQ\r\n"
"MA4GA1UEAxMHUm9vdCBDQTAeFw0yNjA0MTYyMDQ2MTZaFw0zNjA0MDMyMDQ2MTZa\r\n"
"MBQxEjAQBgNVBAMTCWRldmljZS0wMTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IA\r\n"
"BEsrhOKeN6TbfVXVEFVNtlfDi3YHGl2ZCkx80nY12XJSo5MHPqAFVER1VpabqJBo\r\n"
"Vj3+xrJOGrhcrKQ8rmKXY9SjggHIMIIBxDAOBgNVHQ8BAf8EBAMCBaAwKQYDVR0O\r\n"
"BCIEIHRrJvg0matm2JNQlKHCJTK/0W/Zi6y8qCpKNopjg2ilMCsGA1UdIwQkMCKA\r\n"
"IPuczTgNSGcRffM1DPB/20zUMgpoyJJlIItUKxAJhvZYMHMGCCsGAQUFBwEBBGcw\r\n"
"ZTA0BggrBgEFBQcwAYYoaHR0cDovL2Rldi5sYW1hc3N1LnRlc3Q6ODA4MC9hcGkv\r\n"
"dmEvb2NzcDAtBggrBgEFBQcwAYYhaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS92\r\n"
"YS9vY3NwMIHkBgNVHR8EgdwwgdkwbqBsoGqGaGh0dHA6Ly9kZXYubGFtYXNzdS50\r\n"
"ZXN0OjgwODAvYXBpL3ZhL2NybC9mYjljY2QzODBkNDg2NzExN2RmMzM1MGNmMDdm\r\n"
"ZGI0Y2Q0MzIwYTY4Yzg5MjY1MjA4YjU0MmIxMDA5ODZmNjU4MGegZaBjhmFodHRw\r\n"
"Oi8vbG9jYWxob3N0OjgwODAvYXBpL3ZhL2NybC9mYjljY2QzODBkNDg2NzExN2Rm\r\n"
"MzM1MGNmMDdmZGI0Y2Q0MzIwYTY4Yzg5MjY1MjA4YjU0MmIxMDA5ODZmNjU4MAoG\r\n"
"CCqGSM49BAMCA0gAMEUCIQCvF8/WbABttG3Jy6EgqZll/ITztsebHoAQMDqxkWps\r\n"
"kAIgZdNnHMEdn8femZHyT7iR6yxcETBF568qUk2OzbNa5mk=\r\n"
"-----END CERTIFICATE-----\r\n";

static const char bootstrap_key_pem[] =
"-----BEGIN PRIVATE KEY-----\r\n"
"MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQg64cQwihmNFaH7/Wv\r\n"
"l2uyDihAi90q8maF90LPTwEPto2hRANCAARLK4Tinjek231V1RBVTbZXw4t2Bxpd\r\n"
"mQpMfNJ2NdlyUqOTBz6gBVREdVaWm6iQaFY9/sayThq4XKykPK5il2PU\r\n"
"-----END PRIVATE KEY-----\r\n";

#endif /* BOOTSTRAP_CREDENTIALS_H */
