#ifndef CA_CERT_H
#define CA_CERT_H

static const char test_ca_pem[] =
"-----BEGIN CERTIFICATE-----\r\n"
"MIIBvjCCAWOgAwIBAgIUO/fHq2ua+SDNt5ul0jblahvuAx0wCgYIKoZIzj0EAwIw\r\n"
"FDESMBAGA1UEAwwJbG9jYWxob3N0MB4XDTI2MDQyNzE3MDAyOFoXDTM2MDQyNDE3\r\n"
"MDAyOFowFDESMBAGA1UEAwwJbG9jYWxob3N0MFkwEwYHKoZIzj0CAQYIKoZIzj0D\r\n"
"AQcDQgAE7N1MZO0UiiRgSxm79tchv+OIqRWEzUzAGbCOyuaDzWz9o6MR0E+0Hbr/\r\n"
"ji4+aVv4UIDQVg7/tPlCHNlCJHU8pqOBkjCBjzAdBgNVHQ4EFgQUap4df3Uzfg+n\r\n"
"w5CiNxvqPUsF1G0wHwYDVR0jBBgwFoAUap4df3Uzfg+nw5CiNxvqPUsF1G0wDwYD\r\n"
"VR0TAQH/BAUwAwEB/zAaBgNVHREEEzARgglsb2NhbGhvc3SHBH8AAAEwCwYDVR0P\r\n"
"BAQDAgWgMBMGA1UdJQQMMAoGCCsGAQUFBwMBMAoGCCqGSM49BAMCA0kAMEYCIQDS\r\n"
"cLWRLu54lE8GTwQwgkMD2nii/0zHNie/rSLSQtPjWwIhAJLjecURYBCHNiE9efjK\r\n"
"5A2QF+/w19Oc1ZR2UBxVxCMW\r\n"
"-----END CERTIFICATE-----\r\n";

static const char lamassu_proxy_ca_pem[] =
"-----BEGIN CERTIFICATE-----\r\n"
"MIIBjjCCATSgAwIBAgIVAN7drV59obvU/lahfqMU4uVsJUwkMAoGCCqGSM49BAMC\r\n"
"MBQxEjAQBgNVBAMTCWxvY2FsaG9zdDAeFw0yNjA1MDYyMDE5MDNaFw0zNjA1MDYy\r\n"
"MTE5MDNaMBQxEjAQBgNVBAMTCWxvY2FsaG9zdDBZMBMGByqGSM49AgEGCCqGSM49\r\n"
"AwEHA0IABCqsHoWnNrsqvJjQRC33zeS4v8TOTvRoqZuxV4bn4eO42Hw961IwlQZ0\r\n"
"s072otoKlKIXn8UqEP+l6l0sPQGVRESjYzBhMA4GA1UdDwEB/wQEAwIHgDATBgNV\r\n"
"HSUEDDAKBggrBgEFBQcDATAMBgNVHRMBAf8EAjAAMCwGA1UdEQQlMCOCCWxvY2Fs\r\n"
"aG9zdIcEfwAAAYcQAAAAAAAAAAAAAAAAAAAAATAKBggqhkjOPQQDAgNIADBFAiEA\r\n"
"uTGvMunEFV89bO5QDVTZ631sZZ5DotW7iKgxp7h2ekACIAf52rtXeiQxHaAnLCam\r\n"
"Si7R5DD0r/VwoJvWYIO1nuM2\r\n"
"-----END CERTIFICATE-----\r\n";



#endif
