#ifndef CA_CERT_H
#define CA_CERT_H

static const char test_ca_pem[] =
"-----BEGIN CERTIFICATE-----\r\n"
"MIIBeTCCAR+gAwIBAgIUaYLw5HEwprpg4Wyb5c6Bfi5DOoAwCgYIKoZIzj0EAwIw\r\n"
"EjEQMA4GA1UEAwwHVGVzdCBDQTAeFw0yNjA0MTIxNTE5NDhaFw0zNjA0MDkxNTE5\r\n"
"NDhaMBIxEDAOBgNVBAMMB1Rlc3QgQ0EwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNC\r\n"
"AAQmbxf2794hvezrP33QiJJyr4E4Nb2NLfsRmgvbG48F8KppqbXdC2pHW90+p1GS\r\n"
"A41vIZtiMbUgJGSUUK1Cb/u8o1MwUTAdBgNVHQ4EFgQUEQoSVLON1cf9j5IZ9xEF\r\n"
"MoL/UTowHwYDVR0jBBgwFoAUEQoSVLON1cf9j5IZ9xEFMoL/UTowDwYDVR0TAQH/\r\n"
"BAUwAwEB/zAKBggqhkjOPQQDAgNIADBFAiArAQc4mgU5WjJEnevizZT0aZVfrEo/\r\n"
"USIM4m9cFurMugIhAJoXVvSvG/zkbz1CLdtKZisfeiDhw9gUCfsnGpmr58l/\r\n"
"-----END CERTIFICATE-----\r\n";



#endif
