#ifndef CA_CERT_H
#define CA_CERT_H

static const char test_ca_pem[] =
"-----BEGIN CERTIFICATE-----\r\n"
"MIIBdzCCAR2gAwIBAgIQHf0nWHohwABodSHyVLMnOjAKBggqhkjOPQQDAjAUMRIw\r\n"
"EAYDVQQDEwlsb2NhbGhvc3QwHhcNMjYwNDE2MTgzNjI4WhcNMjcwNDE2MTkzNjI4\r\n"
"WjAUMRIwEAYDVQQDEwlsb2NhbGhvc3QwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNC\r\n"
"AAQmegL7ZEIP9R5z5coZ+/AYCAtrcIbuCYtRSbxX9n/6SGR0Jx/ho2fL6WGlu3oq\r\n"
"7lEtBeCP6B/Q9eqkCy86eEJ2o1EwTzAOBgNVHQ8BAf8EBAMCB4AwEwYDVR0lBAww\r\n"
"CgYIKwYBBQUHAwEwDAYDVR0TAQH/BAIwADAaBgNVHREEEzARgglsb2NhbGhvc3SH\r\n"
"BH8AAAEwCgYIKoZIzj0EAwIDSAAwRQIhAIxA18N8ORTAHSFA9Bm9xLePoEh55KUm\r\n"
"BZ2CAomAJ7O2AiB5c/pM266UtSJaF+TBRzxHQMXIn9rDOGpwOcK7Y/IoSg==\r\n"
"-----END CERTIFICATE-----\r\n";



#endif
